services:
  nvidia-trainer:
    container_name: nvidia-trainer
    build:
      context: .
      dockerfile: Dockerfile.nvidia
    ports:
      - "8265:8265"
    volumes:
      - .:/dqn
      - ../durak:/durak
      - ./ray_results:/root/ray_results
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    environment:
      - PYTHONPATH=/dqn/src:/durak/src
      - CUDA_VISIBLE_DEVICES=0
    shm_size: '16gb'
    cap_add:
    - SYS_PTRACE

  amd-trainer:
    container_name: amd-trainer
    build:
      context: .
      dockerfile: Dockerfile.amd
    ports:
      - "8265:8265"
    volumes:
      - .:/dqn
      - ../durak:/durak
      - ./ray_results:/root/ray_results
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    environment:
      - PATH=/opt/venv/bin:$PATH
      - PYTHONPATH=/dqn/src:/durak/src
      - HSA_OVERRIDE_GFX_VERSION=10.3.0
      - CUDA_VISIBLE_DEVICES=0
      - HIP_VISIBLE_DEVICES=0
      - ROCR_VISIBLE_DEVICES=0
    shm_size: '16gb'
    cap_add:
    - SYS_PTRACE

  tensorboard:
    container_name: tensorboard
    build:
      context: .
      dockerfile: Dockerfile.tensorboard
    ports:
      - "6006:6006"
    volumes:
      - ./ray_results:/logs:ro
    restart: unless-stopped
